$(function(){
	$("#jsiHintMsHanbaikosuu").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintMsHanbaikosuuUrl').val(),480,240);
	});
	$("#jsiHintMsSaitakakakutai").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintMsSaitakakakutaiUrl').val(),480,240);
	});
	$("#jsiHintMsKakaku").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintMsKakakuUrl').val(),480,240);
	});
	$("#jsiHintMsKanrihi").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintMsKanrihiUrl').val(),480,240);
	});
	$("#jsiHintMsShuuzentsumitatekin").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintMsShuuzentsumitatekinUrl').val(),480,240);
	});
	$("#jsiHintMsShuuzentsumitatekikin").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintMsShuuzentsumitatekikinUrl').val(),480,240);
	});
	$("#jsiHintMsSyohiyo").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintMsSyohiyoUrl').val(),480,240);
	});
	$("#jsiHintMsMadori").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintMsMadoriUrl').val(),480,240);
	});
	$("#jsiHintMsSennyumenseki").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintMsSennyumensekiUrl').val(),480,240);
	});
	$("#jsiHintMsSonotamenseki").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintMsSonotamensekiUrl').val(),480,240);
	});
	$("#jsiHintMsNyuukyojiki").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintMsNyuukyojikiUrl').val(),480,240);
	});
	$("#jsiHintMsKanseijiki").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintMsKanseijikiUrl').val(),480,240);
	});
	$("#jsiHintMsSyozaikai").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintMsSyozaikaiUrl').val(),480,240);
	});
	$("#jsiHintMsMuki").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintMsMukiUrl').val(),480,240);
	});
	$("#jsiHintMsReform").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintMsReformUrl').val(),480,240);
	});
	$("#jsiHintMsKouzoukaidate").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintMsKouzoukaidateUrl').val(),480,240);
	});
	$("#jsiHintMsSoukosuu").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintMsSoukosuuUrl').val(),480,240);
	});
	$("#jsiHintMsSikichikenri").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintMsSikichikenriUrl').val(),480,240);
	});
	$("#jsiHintMsShikichimenseki").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintMsShikichimensekiUrl').val(),480,240);
	});
	$("#jsiHintMsChushajyou").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintMsChushajyouUrl').val(),480,240);
	});
	$("#jsiHintMsYoutodhiiki").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintMsYoutodhiikiUrl').val(),480,240);
	});
	$("#jsiHintMsSeko").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintMsSekoUrl').val(),480,240);
	});
	$("#jsiHintMsEnerugisyouhiseinou").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintMsEnerugisyouhiseinouUrl').val(),480,240);
	});
	$("#jsiHintMsMeyasukounetsuhi").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintMsMeyasukounetsuhiUrl').val(),480,240);
	});
	$("#jsiHintMsDannetsuseinou").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintMsDannetsuseinouUrl').val(),480,240);
	});
	
	$("#jsiHintKodateHanbaikosuu").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintKodateHanbaikosuuUrl').val(),480,240);
	});
	$("#jsiHintKodateSoukosuu").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintKodateSoukosuuUrl').val(),480,240);
	});
	$("#jsiHintKodateKakaku").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintKodateKakakuUrl').val(),480,240);
	});
	$("#jsiHintKodateSaitakakakutai").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintKodateSaitakakakutaiUrl').val(),480,240);
	});
	$("#jsiHintKodateShidoufutan").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintKodateShidoufutanUrl').val(),480,240);
	});
	$("#jsiHintKodateSyohiyo").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintKodateSyohiyoUrl').val(),480,240);
	});
	$("#jsiHintKodateMadori").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintKodateMadoriUrl').val(),480,240);
	});
	$("#jsiHintKodateTatemonomenseki").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintKodateTatemonomensekiUrl').val(),480,240);
	});
	$("#jsiHintKodateTochimenseki").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintKodateTochimensekiUrl').val(),480,240);
	});
	$("#jsiHintKodateKenpei").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintKodateKenpeiUrl').val(),480,240);
	});
	$("#jsiHintKodateKanseijiki").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintKodateKanseijikiUrl').val(),480,240);
	});
	$("#jsiHintKodateNyuukyojik").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintKodateNyuukyojikUrl').val(),480,240);
	});
	$("#jsiHintKodateTochinokenri").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintKodateTochinokenriUrl').val(),480,240);
	});
	$("#jsiHintKodateKouzoukouhou").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintKodateKouzoukouhouUrl').val(),480,240);
	});
	$("#jsiHintKodateSekou").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintKodateSekouUrl').val(),480,240);
	});
	$("#jsiHintKodateReform").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintKodateReformUrl').val(),480,240);
	});
	$("#jsiHintKodateChushajyou").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintKodateChushajyouUrl').val(),480,240);
	});
	$("#jsiHintKodateChimoku").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintKodateChimokuUrl').val(),480,240);
	});
	$("#jsiHintKodateYoutodhiiki").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintKodateYoutodhiikiUrl').val(),480,240);
	});
	$("#jsiHintKodateEnerugisyouhiseinou").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintKodateEnerugisyouhiseinouUrl').val(),480,240);
	});
	$("#jsiHintKodateMeyasukounetsuhi").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintKodateMeyasukounetsuhiUrl').val(),480,240);
	});	
	$("#jsiHintKodateDannetsuseinou").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintKodateDannetsuseinouUrl').val(),480,240);
	});
	
	$("#jsiHintTochiHanbaikukakusuu").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintTochiHanbaikukakusuuUrl').val(),480,240);
	});
	$("#jsiHintTochiSoukukakusuu").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintTochiSoukukakusuuUrl').val(),480,240);
	});
	$("#jsiHintTochiKakaku").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintTochiKakakuUrl').val(),480,240);
	});
	$("#jsiHintTochiSaitakakakutai").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintTochiSaitakakakutaiUrl').val(),480,240);
	});
	$("#jsiHintTochiShidoufutan").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintTochiShidoufutanUrl').val(),480,240);
	});
	$("#jsiHintTochiSyohiyo").click(function(){
 		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintTochiSyohiyoUrl').val(),480,240);
	});
	$("#jsiHintTochiTochimenseki").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintTochiTochimensekiUrl').val(),480,240);
	});
	$("#jsiHintTochiKenpei").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintTochiKenpeiUrl').val(),480,240);
	});
	$("#jsiHintTochiTochijyokyo").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintTochiTochijyokyoUrl').val(),480,240);
	});
	$("#jsiHintTochiZousei").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintTochiZouseiUrl').val(),480,240);
	});
	$("#jsiHintTochiTochinokenri").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintTochiTochinokenriUrl').val(),480,240);
	});
	$("#jsiHintTochiKenchikujyoken").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintTochiKenchikujyokenUrl').val(),480,240);
	});
	$("#jsiHintTochiHikiwatashijiki").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintTochiHikiwatashijikiUrl').val(),480,240);
	});
	$("#jsiHintTochiChimoku").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintTochiChimokuUrl').val(),480,240);
	});
	$("#jsiHintTochiYoutodhiiki").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintTochiYoutodhiikiUrl').val(),480,240);
	});
	$("#jsiHintKodateKakaku2").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintKodateKakaku2Url').val(),480,240);
	});
	$("#jsiHintKodateMadori2").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintKodateMadori2Url').val(),480,240);
	});
	$("#jsiHintKodateHanbaikosuu2").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintKodateHanbaikosuu2Url').val(),480,240);
	});
	$("#jsiHintKodateSoukosuu2").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintKodateSoukosuu2Url').val(),480,240);
	});
	$("#jsiHintKodateTochimenseki2").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintKodateTochimenseki2Url').val(),480,240);
	});
	$("#jsiHintKodateTatemonomenseki2").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintKodateTatemonomenseki2Url').val(),480,240);
	});
	$("#jsiHintKodateShidoufutan2").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintKodateShidoufutan2Url').val(),480,240);
	});
	$("#jsiHintKodateKanseijiki2").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintKodateKanseijiki2Url').val(),480,240);
	});
	$("#jsiHintMsHanbaikosuu2").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintMsHanbaikosuu2Url').val(),480,240);
	});
	$("#jsiHintMsKakaku2").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintMsKakaku2Url').val(),480,240);
	});
	$("#jsiHintMsMadori2").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintMsMadori2Url').val(),480,240);
	});
	$("#jsiHintMsSennyumenseki2").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintMsSennyumenseki2Url').val(),480,240);
	});
	$("#jsiHintMsSonotamenseki2").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintMsSonotamenseki2Url').val(),480,240);
	});
	$("#jsiHintMsKanseijiki2").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintMsKanseijiki2Url').val(),480,240);
	});
	$("#jsiHintMsSoukosuu2").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintMsSoukosuu2Url').val(),480,240);
	});
	$("#jsiHintMsKouzoukaidate2").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintMsKouzoukaidate2Url').val(),480,240);
	});
	$("#jsiHintTochiHanbaikukakusuu2").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintTochiHanbaikukakusuu2Url').val(),480,240);
	});
	$("#jsiHintTochiSoukukakusuu2").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintTochiSoukukakusuu2Url').val(),480,240);
	});
	$("#jsiHintTochiKakaku2").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintTochiKakaku2Url').val(),480,240);
	});
	$("#jsiHintTochiShidoufutan2").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintTochiShidoufutan2Url').val(),480,240);
	});
	$("#jsiHintTochiTochimenseki2").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintTochiTochimenseki2Url').val(),480,240);
	});
	$("#jsiHintTochiKenpei2").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintTochiKenpei2Url').val(),480,240);
	});
	$("#jsiHintTochiTochijyokyo2").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintTochiTochijyokyo2Url').val(),480,240);
	});
	$("#jsiHintTochiZousei2").click(function(){
		SUUMO.KR_SHOSAI_COMMON.popUp($('#jsiHintTochiZousei2Url').val(),480,240);
	});
});
